package com.ascent.bean;

import java.util.Set;

/**
 * Orders generated by MyEclipse Persistence Tools
 */

public class Orders implements java.io.Serializable {

	// Fields

	private Integer orderid;

	private Integer uid;

	private String temp1;

	private String temp2;

	private String temp3;

	private String temp4;
	
	private String datetime;
	
	private String delsoft;
	//一对多设置字段
	private Set orderitem;

	// Constructors

	public Set getOrderitem() {
		return orderitem;
	}

	public void setOrderitem(Set orderitem) {
		this.orderitem = orderitem;
	}

	/** default constructor */
	public Orders() {
	}

	/** full constructor */
	public Orders(Integer uid, String temp1, String temp2, String temp3,
			String temp4) {
		this.uid = uid;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
	}

	// Property accessors

	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	public String getDatetime() {
		return datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	public String getDelsoft() {
		return delsoft;
	}

	public void setDelsoft(String delsoft) {
		this.delsoft = delsoft;
	}

}