package com.ascent.bean;

/**
 * UserProduct generated by MyEclipse Persistence Tools
 */


@SuppressWarnings("serial")
public class UserProduct implements java.io.Serializable {

	// Fields

	private Integer userProductId;

	private Integer uid;

	private Integer pid;

	// Constructors

	/** default constructor */
	public UserProduct() {
	}

	/** full constructor */
	public UserProduct(Integer uid, Integer pid) {
		this.uid = uid;
		this.pid = pid;
	}

	// Property accessors

	public Integer getUserProductId() {
		return this.userProductId;
	}

	public void setUserProductId(Integer userProductId) {
		this.userProductId = userProductId;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

}